name: Update GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate stats
        run: |
          mkdir -p profile

          curl -L \
            "https://github-readme-stats.vercel.app/api?username=KirtiGautam620&show_icons=true&hide_border=false&title_color=E9A13B&icon_color=5FD3B0&text_color=E6E1D7&bg_color=0E1116&count_private=true&include_all_commits=true" \
            -o profile/stats.svg

          curl -L \
            "https://github-readme-stats.vercel.app/api/top-langs/?username=KirtiGautam620&text_color=E6E1D7&bg_color=0E1116&title_color=E9A13B&langs_count=8&layout=compact&hide_border=false" \
            -o profile/top-langs.svg

      - name: Commit stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/

          git diff --cached --quiet || git commit -m "Update GitHub stats"

          git push
